
# 开启休眠功能
CONFIG_ZMK_SLEEP=y

# 将左手的深度休眠时间也延长至 1小时 (3600000毫秒)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# 增强左手的蓝牙发射功率，确保和右手的连接不断流
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 启用实验性蓝牙连接机制，优化与 Mac 的握手协议
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
