CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y

# --- 休眠与防断连设置 (合并在此处) ---
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# --- 轨迹球 PMW3610 配置 ---
CONFIG_PMW3610=y
CONFIG_PM_DEVICE=y
CONFIG_PMW3610_PM=y

# 灵敏度微调方案：从 2400 降至 1800
# 1800 是一个非常经典的高分屏平衡数值
CONFIG_PMW3610_CPI=1800
CONFIG_PMW3610_CPI_DIVIDOR=1

CONFIG_PMW3610_ORIENTATION_180=y
CONFIG_PMW3610_SNIPE_CPI=400
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=4
CONFIG_PMW3610_SCROLL_TICK=80
CONFIG_PMW3610_INVERT_SCROLL_X=n
CONFIG_PMW3610_INVERT_SCROLL_Y=y
CONFIG_PMW3610_SMART_ALGORITHM=n

# 保持 3264ms 高性能模式，确保起步不肉
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20
CONFIG_PMW3610_POLLING_RATE_125_SW=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=700
CONFIG_PMW3610_MOVEMENT_THRESHOLD=0

# 保留消抖优化
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
