CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

CONFIG_PMW3610=y
CONFIG_PM_DEVICE=y
CONFIG_PMW3610_PM=y

# 灵敏度大幅提升方案
# 1. 基础 CPI 提高到 2400
CONFIG_PMW3610_CPI=2400
# 2. 移除除数限制，设为 1（灵敏度直接翻倍的关键）
CONFIG_PMW3610_CPI_DIVIDOR=1

CONFIG_PMW3610_ORIENTATION_180=y
CONFIG_PMW3610_SNIPE_CPI=400
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=4
CONFIG_PMW3610_SCROLL_TICK=20
CONFIG_PMW3610_INVERT_SCROLL_X=y
CONFIG_PMW3610_INVERT_SCROLL_Y=n
CONFIG_PMW3610_SMART_ALGORITHM=y

# 保持高性能状态 3.2 秒，解决起步延迟
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=500
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20
CONFIG_PMW3610_POLLING_RATE_125_SW=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=700
CONFIG_PMW3610_MOVEMENT_THRESHOLD=0

# 强制 USB 使用 1ms 轮询（理论 1000Hz）
CONFIG_USB_HID_POLLING_INTERVAL_MS=1

# 提高主控处理任务的优先级，防止掉帧
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
